apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: {{ .Values.label }}
  replicas: {{ .Values.replicacount }} # tells deployment to run replicas pods matching the template
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.service.containerport }}
        volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html
      
      volumes:
      - name: nginx
        configMap:
          name: helm-config